package ch.csbe.backendlb.resources.user.authentifikation;

import lombok.Data;

@Data // Lombok annotation to generate getters, setters, and other boilerplate code
public class TokenWrapper {
    private String token; // A string field to store the JWT token

    // Getter and setter methods for the 'token' field are automatically generated by Lombok.
}
